### PR TITLE
Implement KDE / KWallet support on Linux

### PR DESCRIPTION
**Pull request by glutanimate**
Hi! Thanks first of all for this awesome project. It has made my life a whole lot easier!

Right now `pycookiecheat` won't work properly on KDE. This seems to be because [KDE has yet to adhere to the Secret Service DBus standard](https://github.com/jaraco/keyring/issues/273#issuecomment-379470367), causing  passphrase look-ups through libsecret to fail (with similar errors as the ones in #18).

On KDE, Chrome/Chromium defaults to using KDE's own key storage, KWallet. Fortunately enough this storage is supported by `keyring` (at least as long as the `dbus-python` package is installed as well).

This PR seeks to implement KDE / KWallet suppport by adding a fallback to `keyring` when gathering the passphrase.

It might also be worth considering switching to keyring on Linux entirely, but I didn't want to submit any changes that would be too comprehensive, especially given that I wouldn't have enough time to test them properly.

### CODE REVIEW

**Comment by glutanimate** [comment]
Sorry about that. Forgot about cases where keyring had no backends at all. Builds should hopefully pass now.

**Comment by n8henrie** [comment]
Thanks for the contribution.

Before merging, would you add a line to the README's FAQ about manually installing the dbus dependency for people wanting to use with KDE?

I'm also going to change the PR to the dev branch.

**Comment by n8henrie** [comment]
@glutanimate -- any chance you'd be willing to make those changes?

**Comment by glutanimate** [comment]
Sorry, @n8henrie, completely lost track of this PR. Hope the commit I just added is ok.

**Comment by n8henrie** [comment]
Looks great, thanks.

Re: failures -- I really hate these pycodestyle plugin issues that have been plaguing flake8 for like a year now.

**Pull request merged**
