### PR TITLE
Update keyring username for Slack.

### PR DESCRIPTION
**Pull request by hraftery**
## Description

Just chasing the ever-changing internal details of Slack. Not sure when this change happened, it may have been quite some time ago, but it is present in version 4.39.95 of Slack for Mac.

### CODE REVIEW

**Comment by n8henrie** [comment]
@hraftery so it sounds like you've tested this (and it's working) locally?

**Comment by n8henrie** [comment]
(Also, thanks for the PR!)

**Comment by hraftery** [comment]
> so it sounds like you've tested this (and it's working) locally?

Correct, yes.

**Comment by n8henrie** [comment]
Great, thanks!

**Pull request merged**
