### PR TITLE
Allow the user to pass in a custom password

### PR DESCRIPTION
**Pull request by alairock**
In Ubuntu, they don't use 'peanuts', so this will attempt to get the password from chrome itself. This has been tested manually and works, ubuntu 19.04, chrome 76.0.3809.132, Python 3.7

### CODE REVIEW

**Comment by n8henrie** [comment]
Thanks for your interest in contributing.

It looks like this might break all other platforms:

1. you removed the `.encode` [here](https://github.com/n8henrie/pycookiecheat/blob/209585560189b9ca4f00f42ca6f315b9b2b37f26/src/pycookiecheat/pycookiecheat.py#L187), which is likely not to work well.
2. as the CI suggests, the library you're using to pull in the password is throwing a fit when things like `DBUS_SESSION_BUS_ADDRESS` aren't defined.

Additionally, I'd prefer not to pull in additional third party code if I can help it.

Instead, what about an alternative route -- we could just add a `password` kwarg where users could pass in their own, if they know it. Have it default to `None`, in which case it uses the default as before (so it should remain backwards compatible).

That way Ubuntu users could use whatever libraries they'd like to pull in the password, and then just pass it into the function.

I may even remove the `keyring` dependency from the OSX function now that I'm thinking about it.

Thoughts?

**Comment by alairock** [comment]
@n8henrie yeah. That is a great idea, actually. That is a much better approach.

**Comment by alairock** [comment]
Got into a weird state using the github editor, but this last commit should work fine. 

Tests are passing, but the linter seems to be having a bad day. Not sure if that is from me though: 
https://travis-ci.org/n8henrie/pycookiecheat/jobs/581447860#L282

**Comment by n8henrie** [comment]
Gah. All those pycodestyle errors have become such a pain. I'll look into it.

**Comment by n8henrie** [comment]
Bump @alairock -- would you mind implementing those changes?

**Comment by alairock** [comment]
Sorry, wasn't watching my notifications closely enough. 

Not sure I understand. Do you no longer want to pass the password as keyword arguments? And instead use the `secretstorage` mechanism in my initial commit inside the `get_linux_config` function? Or have I missed what you meant entirely?

**Comment by n8henrie** [comment]
No, for a minute I was thinking perhaps of passing in a config dict so that other parts of the config could be manually overridden, but I think for now just passing in password is fine.

I was recommending that instead of using a ternary `password if password is not None else config['my_pass'].encode('utf8')` that it would seem more readable to do something like:

```python
if password is not None:
    config.update({"password": password})
```

Also, do you think password should be passed in as `str` and then encoded? Or should it be encoded by the user and passed in as `bytes`? I'm no encoding expert.

**Comment by alairock** [comment]
I wouldn't consider myself an expert in encoding either, though my preference as a user is to not to have to worry about it when I am using a library. 

In the code wouldn't it actually need to be:
```
if password is not None:
    config.update({"my_pass": password})
```

**Comment by n8henrie** [comment]
Yes, looks like it is `my_pass`. Thanks.

**Comment by alairock** [comment]
Updated.

**Comment by n8henrie** [comment]
Man, that lint error was killing me. Thanks for your contribution @alairock. Can you pull the dev branch and make sure that it fits your use case?

**Comment by alairock** [comment]
Looks like it's working fine for me :)

**Pull request merged**
